package one.zrp.social.mobile.solana

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Test
import java.math.BigInteger

/**
 * Every expected value below was generated by actually running
 * src/lib/launchpad/zrp-launch-keys.ts (via ts-node, in this repo) - the
 * real, already-proven-correct TS source this Kotlin file ports - not
 * hand-derived or assumed. See the commit introducing this file for the
 * generation script. If ZrpLaunchpad disagrees with any of these, the
 * Kotlin port has a real bug, not a test-authoring one.
 */
class ZrpLaunchpadTest {

    @Test
    fun `buy quotes match the real TS source exactly`() {
        data class Case(val vSol: Long, val vTok: Long, val solIn: Long, val feeBps: Int, val tokenOut: String, val feeLamports: String)
        val cases = listOf(
            Case(30_000_000_000L, 1_073_000_000_000_000L, 1_000_000_000L, 100, "34277831558567", "10000000"),
            Case(30_000_000_000L, 1_073_000_000_000_000L, 5_000_000_000L, 100, "151969957081545", "50000000"),
            Case(42_000_000_123L, 850_000_000_456_789L, 123_456_789L, 50, "2478787780589", "617283"),
            Case(1_000_000L, 1_000_000_000_000L, 999_999_999_999L, 250, "999998974360", "24999999999"),
        )
        for (c in cases) {
            val quote = ZrpLaunchpad.quoteZrpBuy(
                BigInteger.valueOf(c.vSol), BigInteger.valueOf(c.vTok), BigInteger.valueOf(c.solIn), c.feeBps
            )
            assertEquals(c.tokenOut, quote.tokenOut.toString())
            assertEquals(c.feeLamports, quote.feeLamports.toString())
        }
    }

    @Test
    fun `sell quotes match the real TS source exactly`() {
        data class Case(val vSol: Long, val vTok: Long, val tokenIn: Long, val feeBps: Int, val solOut: String, val feeLamports: String)
        val cases = listOf(
            Case(30_000_000_000L, 1_073_000_000_000_000L, 10_000_000_000_000L, 100, "274238228", "2770083"),
            Case(42_000_000_123L, 850_000_000_456_789L, 999_999_999_999L, 50, "49106934", "246768"),
        )
        for (c in cases) {
            val quote = ZrpLaunchpad.quoteZrpSell(
                BigInteger.valueOf(c.vSol), BigInteger.valueOf(c.vTok), BigInteger.valueOf(c.tokenIn), c.feeBps
            )
            assertEquals(c.solOut, quote.solOut.toString())
            assertEquals(c.feeLamports, quote.feeLamports.toString())
        }
    }

    @Test
    fun `slippage helpers match the real TS source`() {
        assertEquals("950000", ZrpLaunchpad.applySlippageDown(BigInteger.valueOf(1_000_000), 500).toString())
        assertEquals("1050000", ZrpLaunchpad.applySlippageUp(BigInteger.valueOf(1_000_000), 500).toString())
    }

    @Test
    fun `anchor discriminators match the real TS source`() {
        fun hex(bytes: ByteArray) = bytes.joinToString("") { "%02x".format(it) }
        assertEquals("45a6cc9138421c79", hex(ZrpLaunchpad.anchorDiscriminator("global", "create_and_buy")))
        assertEquals("66063d1201daebea", hex(ZrpLaunchpad.anchorDiscriminator("global", "buy")))
        assertEquals("33e685a4017f83ad", hex(ZrpLaunchpad.anchorDiscriminator("global", "sell")))
        assertEquals("2debe1b511da4082", hex(ZrpLaunchpad.anchorDiscriminator("global", "graduate")))
    }

    @Test
    fun `create_and_buy instruction encoding matches the real TS source byte-for-byte`() {
        val expected = "45a6cc9138421c790e0000005a5250205465737420546f6b656e040000005a5250543600000068747470733a2f2f7a72702e6f6e652f6170692f6c61756e63687061642f746f6b656e732f58595a2f6d657461646174612e6a736f6e009435770000000040e2010000000000"
        val ix = ZrpLaunchpad.encodeCreateAndBuyIx(
            name = "ZRP Test Token",
            symbol = "ZRPT",
            uri = "https://zrp.one/api/launchpad/tokens/XYZ/metadata.json",
            initialBuyLamports = BigInteger.valueOf(2_000_000_000),
            minTokensOut = BigInteger.valueOf(123_456),
        )
        assertEquals(expected, ix.joinToString("") { "%02x".format(it) })
    }

    @Test
    fun `buy instruction encoding matches the real TS source byte-for-byte`() {
        val expected = "66063d1201daebea002f6859000000003f420f0000000000"
        val ix = ZrpLaunchpad.encodeBuyIx(BigInteger.valueOf(1_500_000_000), BigInteger.valueOf(999_999))
        assertEquals(expected, ix.joinToString("") { "%02x".format(it) })
    }

    @Test
    fun `sell instruction encoding matches the real TS source byte-for-byte`() {
        val expected = "33e685a4017f83ad002465c70900000031de0b0000000000"
        val ix = ZrpLaunchpad.encodeSellIx(BigInteger.valueOf(42_000_000_000), BigInteger.valueOf(777_777))
        assertEquals(expected, ix.joinToString("") { "%02x".format(it) })
    }

    @Test
    fun `graduate instruction is just its discriminator`() {
        assertArrayEquals(ZrpLaunchpad.anchorDiscriminator("global", "graduate"), ZrpLaunchpad.encodeGraduateIx())
    }

    @Test
    fun `derived PDAs match the real TS source and the real devnet addresses`() {
        val mint = SolanaPublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v")
        val keys = ZrpLaunchpad.deriveZrpLaunchKeys(mint, ZrpLaunchpad.DEVNET_PROGRAM_ID)
        assertEquals("9c7PdQJ4ZYyMivTog68uAo7LWNcuNKghzyi8AfRqAQy3", keys.globalConfig.toBase58())
        assertEquals("8UB5dEutCq9wjjE9BzmCB6pFmKoDTBqi7q8jLNDeAUrj", keys.bondingCurve.toBase58())
        assertEquals("5x38Kp4hvdomTCnCrAny4UtMUt5rQBdB6px2K1Ui45Wq", keys.metadata.toBase58())
    }

    @Test
    fun `GlobalConfig decoding round-trips a hand-built account buffer`() {
        // Hand-assembled using the exact field layout documented in
        // zrp-launch-keys.ts's own decodeGlobalConfig - this is a
        // structural round-trip test (encode then decode), complementing
        // the cross-language vectors above which cover the instruction
        // *encoding* side; there is no equivalent TS decode-side fixture
        // to diff against since the TS source never ships a canned
        // GlobalConfig buffer either.
        val authority = SolanaPublicKey("3vr1SHa9LvEvELb23NBG1J6oFRCSDs8cj8wS55zuoRxK")
        val feeRecipient = SolanaPublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v")
        val migrationAuthority = SolanaPublicKey("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
        val buf = ByteArray(8) + authority.bytes + feeRecipient.bytes + migrationAuthority.bytes +
            u64LEBytes(BigInteger.valueOf(2_000_000)) + // creationFeeLamports
            byteArrayOf(0x64, 0x00) + // buyFeeBps = 100
            byteArrayOf(0xC8.toByte(), 0x00) + // sellFeeBps = 200
            u64LEBytes(BigInteger.valueOf(30_000_000_000)) + // initialVirtualSolReserves
            u64LEBytes(BigInteger.valueOf(1_073_000_000_000_000)) + // initialVirtualTokenReserves
            u64LEBytes(BigInteger.valueOf(1_000_000_000_000_000)) + // tokenTotalSupply
            u64LEBytes(BigInteger.valueOf(5_000_000_000)) + // graduationSolTarget
            byteArrayOf(6) + // tokenDecimals
            byteArrayOf(254.toByte()) // bump

        val decoded = ZrpLaunchpad.decodeGlobalConfig(buf)
        assertEquals(authority, decoded.authority)
        assertEquals(feeRecipient, decoded.feeRecipient)
        assertEquals(migrationAuthority, decoded.migrationAuthority)
        assertEquals(BigInteger.valueOf(2_000_000), decoded.creationFeeLamports)
        assertEquals(100, decoded.buyFeeBps)
        assertEquals(200, decoded.sellFeeBps)
        assertEquals(BigInteger.valueOf(30_000_000_000), decoded.initialVirtualSolReserves)
        assertEquals(BigInteger.valueOf(1_073_000_000_000_000), decoded.initialVirtualTokenReserves)
        assertEquals(BigInteger.valueOf(1_000_000_000_000_000), decoded.tokenTotalSupply)
        assertEquals(BigInteger.valueOf(5_000_000_000), decoded.graduationSolTarget)
        assertEquals(6, decoded.tokenDecimals)
        assertEquals(254, decoded.bump)
    }

    @Test
    fun `BondingCurve decoding round-trips a hand-built account buffer`() {
        val mint = SolanaPublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v")
        val creator = SolanaPublicKey("3vr1SHa9LvEvELb23NBG1J6oFRCSDs8cj8wS55zuoRxK")
        val buf = ByteArray(8) + mint.bytes + creator.bytes +
            u64LEBytes(BigInteger.valueOf(31_000_000_000)) + // virtualSolReserves
            u64LEBytes(BigInteger.valueOf(1_038_722_168_441_433)) + // virtualTokenReserves
            u64LEBytes(BigInteger.valueOf(1_000_000_000)) + // realSolReserves
            u64LEBytes(BigInteger.valueOf(34_277_831_558_567)) + // realTokenReserves
            u64LEBytes(BigInteger.valueOf(1_000_000_000_000_000)) + // tokenTotalSupply
            byteArrayOf(0) + // complete = false
            byteArrayOf(0) + // migrated = false
            u64LEBytes(BigInteger.valueOf(1_700_000_000)) + // createdAt
            byteArrayOf(255.toByte()) // bump

        val decoded = ZrpLaunchpad.decodeBondingCurve(buf)
        assertEquals(mint, decoded.mint)
        assertEquals(creator, decoded.creator)
        assertEquals(BigInteger.valueOf(31_000_000_000), decoded.virtualSolReserves)
        assertEquals(BigInteger.valueOf(1_038_722_168_441_433), decoded.virtualTokenReserves)
        assertEquals(BigInteger.valueOf(1_000_000_000), decoded.realSolReserves)
        assertEquals(BigInteger.valueOf(34_277_831_558_567), decoded.realTokenReserves)
        assertEquals(BigInteger.valueOf(1_000_000_000_000_000), decoded.tokenTotalSupply)
        assertEquals(false, decoded.complete)
        assertEquals(false, decoded.migrated)
        assertEquals(BigInteger.valueOf(1_700_000_000), decoded.createdAt)
        assertEquals(255, decoded.bump)
    }

    @Test
    fun `TradeEvent parsing extracts a real base64-logged event`() {
        // Hand-assembled using the exact event:TradeEvent discriminator
        // and field layout from zrp-launch-keys.ts's parseTradeEvents.
        val mint = SolanaPublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v")
        val trader = SolanaPublicKey("3vr1SHa9LvEvELb23NBG1J6oFRCSDs8cj8wS55zuoRxK")
        val body = mint.bytes + trader.bytes +
            byteArrayOf(1) + // isBuy = true
            u64LEBytes(BigInteger.valueOf(1_000_000_000)) + // solAmount
            u64LEBytes(BigInteger.valueOf(34_277_831_558_567)) + // tokenAmount
            u64LEBytes(BigInteger.valueOf(10_000_000)) + // feeLamports
            u64LEBytes(BigInteger.valueOf(31_000_000_000)) + // virtualSolReserves
            u64LEBytes(BigInteger.valueOf(1_038_722_168_441_433)) + // virtualTokenReserves
            u64LEBytes(BigInteger.valueOf(1_000_000_000)) + // realSolReserves
            u64LEBytes(BigInteger.valueOf(34_277_831_558_567)) + // realTokenReserves
            u64LEBytes(BigInteger.valueOf(1_700_000_000)) // timestamp
        val full = ZrpLaunchpad.anchorDiscriminator("event", "TradeEvent") + body
        val logLine = "Program data: " + java.util.Base64.getEncoder().encodeToString(full)

        val events = ZrpLaunchpad.parseTradeEvents(listOf("some other log", logLine, "Program log: unrelated"))
        assertEquals(1, events.size)
        val event = events[0]
        assertEquals(mint, event.mint)
        assertEquals(trader, event.trader)
        assertEquals(true, event.isBuy)
        assertEquals(BigInteger.valueOf(1_000_000_000), event.solAmount)
        assertEquals(BigInteger.valueOf(34_277_831_558_567), event.tokenAmount)
        assertEquals(BigInteger.valueOf(1_700_000_000), event.timestamp)
    }

    @Test
    fun `event parsing rejects logs from a different discriminator`() {
        // A TradeEvent-shaped body under a DIFFERENT event name's
        // discriminator must never be picked up as a TradeEvent - this is
        // the authoritative-event-only guarantee the mission requires.
        val mint = SolanaPublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v")
        val body = mint.bytes + ByteArray(100)
        val wrongDiscriminator = ZrpLaunchpad.anchorDiscriminator("event", "SomeUnrelatedEvent") + body
        val logLine = "Program data: " + java.util.Base64.getEncoder().encodeToString(wrongDiscriminator)
        assertEquals(0, ZrpLaunchpad.parseTradeEvents(listOf(logLine)).size)
    }
}
