import {
  Keypair,
  PublicKey,
  SystemProgram,
  Transaction,
  ComputeBudgetProgram,
} from "@solana/web3.js";
import {
  getAssociatedTokenAddressSync,
  createAssociatedTokenAccountInstruction,
  createInitializeMintInstruction,
  createMintToInstruction,
  createSetAuthorityInstruction,
  AuthorityType,
  MINT_SIZE,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import { prisma } from "@/lib/db";
import { getConnection, getPlatformWallet } from "@/lib/solana";
import {
  buildCreateMetadataInstruction,
  buildCreateNftMetadataInstruction,
  buildCreateMasterEditionInstruction,
  buildUpdateNftAuthorityInstruction,
  METADATA_BURN_ADDRESS,
} from "./metaplex-metadata";

/*
 * ============================================================
 * ZRP Launchpad - server-signed SPL token minting
 * ============================================================
 *
 * The platform Keypair (the same one src/lib/solana.ts's sendUsdc()/
 * withdrawals use) is the sole signer and fee payer for the entire mint
 * transaction. It briefly holds mint+freeze authority itself (required,
 * since initializeMint/mintTo/createMetadataAccountV3 all need a live
 * authority signature) and hands both off - or revokes them outright -
 * to the creator's verified wallet as the LAST instructions in the same
 * transaction. The creator's wallet never signs anything and is never
 * asked to; see prisma/schema.prisma's LaunchedToken model comment and
 * the Phase 1 plan for the full reasoning.
 *
 */

export interface MintLaunchedTokenParams {
  launchedTokenId: string;
  ownerWalletAddress: string; // creator's verified Solana wallet (base58)
  // Generated by the caller (not here) so the mint address is known
  // BEFORE this runs, letting the caller embed it in the metadata URI
  // it passes in (GET /api/launchpad/tokens/[mint]/metadata.json) - a
  // keypair's public key is meaningful/public before anything ever
  // touches it on-chain, so there's no ordering problem in knowing it
  // this early.
  mintKeypair: Keypair;
  name: string;
  symbol: string;
  metadataUri: string;
  decimals: number;
  supply: bigint; // already in raw base units (supply * 10^decimals)
  revokeMint: boolean;
  revokeFreeze: boolean;
  revokeUpdate: boolean;
}

/**
 * Persists the broadcast signature + mint address the instant they're
 * known, deliberately before confirmation is awaited - same crash-safety
 * shape as withdrawals.ts's recordTransactionHash(). A crash after this
 * line still leaves a durable pointer at exactly which on-chain mint this
 * row produced, even though there is no reconciliation job yet (Phase 1
 * scope: a stuck PENDING row with a recorded mintTransactionId can be
 * checked against Solana by hand until that job exists).
 */
async function recordBroadcast(launchedTokenId: string, signature: string, mintAddress: string, attempts = 3): Promise<void> {
  let lastError: unknown;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      await prisma.launchedToken.update({
        where: { id: launchedTokenId },
        data: { mintTransactionId: signature, mintAddress },
      });
      return;
    } catch (error) {
      lastError = error;
      if (attempt < attempts) {
        await new Promise((resolve) => setTimeout(resolve, 200 * attempt));
      }
    }
  }
  console.error(
    `CRITICAL: launched token ${launchedTokenId} broadcast on-chain (signature ${signature}, mint ${mintAddress}) but failed to persist after ${attempts} attempts.`,
    lastError
  );
}

async function markStatus(launchedTokenId: string, status: "COMPLETED" | "FAILED", failureReason?: string): Promise<void> {
  await prisma.launchedToken.update({
    where: { id: launchedTokenId },
    data: { status, failureReason: failureReason ?? null },
  });
}

// Exported for unit testing (src/lib/launchpad/__tests__/mint-service.test.ts)
// - pure instruction construction, no RPC call, so it's tested directly
// rather than through mintLaunchedToken()'s network-touching wrapper.
export function buildMintTransaction(params: {
  platformPubkey: PublicKey;
  mintPubkey: PublicKey;
  ownerPubkey: PublicKey;
  mintRent: number;
  decimals: number;
  supply: bigint;
  name: string;
  symbol: string;
  metadataUri: string;
  revokeMint: boolean;
  revokeFreeze: boolean;
  revokeUpdate: boolean;
}): Transaction {
  const {
    platformPubkey,
    mintPubkey,
    ownerPubkey,
    mintRent,
    decimals,
    supply,
    name,
    symbol,
    metadataUri,
    revokeMint,
    revokeFreeze,
    revokeUpdate,
  } = params;

  const transaction = new Transaction();
  transaction.feePayer = platformPubkey;

  transaction.add(ComputeBudgetProgram.setComputeUnitLimit({ units: 400_000 }));

  transaction.add(
    SystemProgram.createAccount({
      fromPubkey: platformPubkey,
      newAccountPubkey: mintPubkey,
      space: MINT_SIZE,
      lamports: mintRent,
      programId: TOKEN_PROGRAM_ID,
    }),
    // Platform holds mint + freeze authority TEMPORARILY - required so it
    // can sign mintTo/createMetadataAccountV3 below. Handed off/revoked
    // at the end of this same transaction.
    createInitializeMintInstruction(mintPubkey, decimals, platformPubkey, platformPubkey, TOKEN_PROGRAM_ID)
  );

  const ownerAta = getAssociatedTokenAddressSync(
    mintPubkey,
    ownerPubkey,
    false,
    TOKEN_PROGRAM_ID,
    ASSOCIATED_TOKEN_PROGRAM_ID
  );
  transaction.add(
    createAssociatedTokenAccountInstruction(
      platformPubkey,
      ownerAta,
      ownerPubkey,
      mintPubkey,
      TOKEN_PROGRAM_ID,
      ASSOCIATED_TOKEN_PROGRAM_ID
    )
  );

  transaction.add(createMintToInstruction(mintPubkey, ownerAta, platformPubkey, supply, [], TOKEN_PROGRAM_ID));

  transaction.add(
    buildCreateMetadataInstruction({
      mint: mintPubkey,
      mintAuthority: platformPubkey,
      payer: platformPubkey,
      updateAuthority: revokeUpdate ? METADATA_BURN_ADDRESS : ownerPubkey,
      name,
      symbol,
      metadataUri,
      isMutable: !revokeUpdate,
    })
  );

  // Hand off / revoke mint + freeze authority LAST, once every prior
  // instruction that still needed the platform to hold them has already
  // been added above.
  transaction.add(
    createSetAuthorityInstruction(
      mintPubkey,
      platformPubkey,
      AuthorityType.MintTokens,
      revokeMint ? null : ownerPubkey,
      [],
      TOKEN_PROGRAM_ID
    )
  );
  transaction.add(
    createSetAuthorityInstruction(
      mintPubkey,
      platformPubkey,
      AuthorityType.FreezeAccount,
      revokeFreeze ? null : ownerPubkey,
      [],
      TOKEN_PROGRAM_ID
    )
  );

  return transaction;
}

/**
 * Builds, signs, broadcasts and confirms the mint transaction for an
 * already-created LaunchedToken row (status PENDING, fee already
 * verified and claimed by the caller). Never throws for an on-chain
 * failure - the LaunchedToken row's status/failureReason is the result;
 * callers read that back rather than catching. Does throw for a
 * programmer error (e.g. an invalid wallet address that should have been
 * validated before this was ever called).
 */
export async function mintLaunchedToken(params: MintLaunchedTokenParams): Promise<void> {
  const {
    launchedTokenId,
    ownerWalletAddress,
    mintKeypair,
    name,
    symbol,
    metadataUri,
    decimals,
    supply,
    revokeMint,
    revokeFreeze,
    revokeUpdate,
  } = params;

  const ownerPubkey = new PublicKey(ownerWalletAddress);

  const connection = getConnection();
  const platform = getPlatformWallet();

  // Rent for the ATA + metadata accounts is resolved by their own
  // create-account instruction builders internally; only the mint
  // account's rent is computed explicitly since its createAccount is
  // built by hand above.
  let mintRent: number;
  try {
    mintRent = await connection.getMinimumBalanceForRentExemption(MINT_SIZE);
  } catch (error) {
    await markStatus(launchedTokenId, "FAILED", "Failed to query Solana for rent-exemption amounts.");
    console.error(`Launchpad mint ${launchedTokenId}: rent query failed:`, error);
    return;
  }

  const transaction = buildMintTransaction({
    platformPubkey: platform.publicKey,
    mintPubkey: mintKeypair.publicKey,
    ownerPubkey,
    mintRent,
    decimals,
    supply,
    name,
    symbol,
    metadataUri,
    revokeMint,
    revokeFreeze,
    revokeUpdate,
  });

  let signature: string;
  try {
    const { blockhash, lastValidBlockHeight } = await connection.getLatestBlockhash("finalized");
    transaction.recentBlockhash = blockhash;
    transaction.sign(platform, mintKeypair);

    signature = await connection.sendRawTransaction(transaction.serialize(), {
      skipPreflight: false,
      maxRetries: 3,
      preflightCommitment: "confirmed",
    });

    // Durable checkpoint - written the instant broadcast succeeds, before
    // confirmation is awaited. See recordBroadcast()'s own comment.
    await recordBroadcast(launchedTokenId, signature, mintKeypair.publicKey.toBase58());

    const confirmation = await connection.confirmTransaction(
      { signature, blockhash, lastValidBlockHeight },
      "confirmed"
    );

    if (confirmation.value.err) {
      await markStatus(launchedTokenId, "FAILED", `Transaction failed on-chain: ${JSON.stringify(confirmation.value.err)}`);
      return;
    }
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error while minting.";
    console.error(`Launchpad mint ${launchedTokenId}: mint transaction error:`, error);
    // A broadcast signature was already recorded (recordBroadcast ran)
    // whenever sendRawTransaction itself succeeded - only confirmation
    // can throw past that point, and the on-chain outcome is then
    // genuinely ambiguous to this process (same class of ambiguity
    // withdrawals.ts documents for sendUsdc()). Phase 1 deliberately
    // does not ship a reconciliation job for this; the recorded
    // mintTransactionId is what an operator would check by hand.
    await markStatus(launchedTokenId, "FAILED", message);
    return;
  }

  await markStatus(launchedTokenId, "COMPLETED");
}

// ============================================================
// Phase 6a: NFT minting
// ============================================================

export interface MintLaunchedNftParams {
  launchedNftId: string;
  ownerWalletAddress: string;
  mintKeypair: Keypair;
  name: string;
  symbol: string;
  metadataUri: string;
  sellerFeeBasisPoints: number;
  revokeUpdate: boolean;
}

async function recordNftBroadcast(launchedNftId: string, signature: string, mintAddress: string, attempts = 3): Promise<void> {
  let lastError: unknown;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      await prisma.launchedNft.update({
        where: { id: launchedNftId },
        data: { mintTransactionId: signature, mintAddress },
      });
      return;
    } catch (error) {
      lastError = error;
      if (attempt < attempts) {
        await new Promise((resolve) => setTimeout(resolve, 200 * attempt));
      }
    }
  }
  console.error(
    `CRITICAL: launched NFT ${launchedNftId} broadcast on-chain (signature ${signature}, mint ${mintAddress}) but failed to persist after ${attempts} attempts.`,
    lastError
  );
}

async function markNftStatus(launchedNftId: string, status: "COMPLETED" | "FAILED", failureReason?: string): Promise<void> {
  await prisma.launchedNft.update({
    where: { id: launchedNftId },
    data: { status, failureReason: failureReason ?? null },
  });
}

// Exported for unit testing, same rationale as buildMintTransaction above.
// Always supply=1/decimals=0 (a 1-of-1 NFT) - unlike buildMintTransaction
// there is no revokeMint/revokeFreeze choice, since
// buildCreateMasterEditionInstruction consumes/transfers both
// authorities to the edition PDA itself as a side effect; the only
// authority choice an NFT creator makes is revokeUpdate (freeze the
// metadata permanently).
export function buildMintNftTransaction(params: {
  platformPubkey: PublicKey;
  mintPubkey: PublicKey;
  ownerPubkey: PublicKey;
  mintRent: number;
  name: string;
  symbol: string;
  metadataUri: string;
  sellerFeeBasisPoints: number;
  revokeUpdate: boolean;
}): Transaction {
  const { platformPubkey, mintPubkey, ownerPubkey, mintRent, name, symbol, metadataUri, sellerFeeBasisPoints, revokeUpdate } = params;

  const transaction = new Transaction();
  transaction.feePayer = platformPubkey;

  transaction.add(ComputeBudgetProgram.setComputeUnitLimit({ units: 400_000 }));

  transaction.add(
    SystemProgram.createAccount({
      fromPubkey: platformPubkey,
      newAccountPubkey: mintPubkey,
      space: MINT_SIZE,
      lamports: mintRent,
      programId: TOKEN_PROGRAM_ID,
    }),
    createInitializeMintInstruction(mintPubkey, 0, platformPubkey, platformPubkey, TOKEN_PROGRAM_ID)
  );

  const ownerAta = getAssociatedTokenAddressSync(
    mintPubkey,
    ownerPubkey,
    false,
    TOKEN_PROGRAM_ID,
    ASSOCIATED_TOKEN_PROGRAM_ID
  );
  transaction.add(
    createAssociatedTokenAccountInstruction(
      platformPubkey,
      ownerAta,
      ownerPubkey,
      mintPubkey,
      TOKEN_PROGRAM_ID,
      ASSOCIATED_TOKEN_PROGRAM_ID
    )
  );

  transaction.add(createMintToInstruction(mintPubkey, ownerAta, platformPubkey, BigInt(1), [], TOKEN_PROGRAM_ID));

  // Metadata is created with the PLATFORM as update authority - it has
  // to be, since createCreateMasterEditionV3 below requires the
  // metadata's CURRENT update authority to sign, and the owner wallet
  // never signs anything in this launchpad. Handed off to its real
  // final value (the owner, or the burn address if revoked) by the
  // standalone update-authority instruction at the very end, once
  // nothing platform-signed still needs it.
  transaction.add(
    buildCreateNftMetadataInstruction({
      mint: mintPubkey,
      mintAuthority: platformPubkey,
      payer: platformPubkey,
      updateAuthority: platformPubkey,
      creatorAddress: ownerPubkey,
      name,
      symbol,
      metadataUri,
      sellerFeeBasisPoints,
      isMutable: !revokeUpdate,
    })
  );

  // Consumes/transfers the mint's own mint+freeze authority to the
  // edition PDA as a side effect - no separate createSetAuthorityInstruction
  // calls needed here, unlike the fungible-token mint path.
  transaction.add(
    buildCreateMasterEditionInstruction({
      mint: mintPubkey,
      updateAuthority: platformPubkey,
      mintAuthority: platformPubkey,
      payer: platformPubkey,
    })
  );

  transaction.add(
    buildUpdateNftAuthorityInstruction({
      mint: mintPubkey,
      currentAuthority: platformPubkey,
      newAuthority: revokeUpdate ? METADATA_BURN_ADDRESS : ownerPubkey,
    })
  );

  return transaction;
}

/**
 * Builds, signs, broadcasts and confirms the mint transaction for an
 * already-created LaunchedNft row (status PENDING, fee already verified
 * and claimed by the caller). Same never-throws-for-on-chain-failure
 * contract as mintLaunchedToken().
 */
export async function mintLaunchedNft(params: MintLaunchedNftParams): Promise<void> {
  const { launchedNftId, ownerWalletAddress, mintKeypair, name, symbol, metadataUri, sellerFeeBasisPoints, revokeUpdate } = params;

  const ownerPubkey = new PublicKey(ownerWalletAddress);

  const connection = getConnection();
  const platform = getPlatformWallet();

  let mintRent: number;
  try {
    mintRent = await connection.getMinimumBalanceForRentExemption(MINT_SIZE);
  } catch (error) {
    await markNftStatus(launchedNftId, "FAILED", "Failed to query Solana for rent-exemption amounts.");
    console.error(`Launchpad NFT mint ${launchedNftId}: rent query failed:`, error);
    return;
  }

  const transaction = buildMintNftTransaction({
    platformPubkey: platform.publicKey,
    mintPubkey: mintKeypair.publicKey,
    ownerPubkey,
    mintRent,
    name,
    symbol,
    metadataUri,
    sellerFeeBasisPoints,
    revokeUpdate,
  });

  let signature: string;
  try {
    const { blockhash, lastValidBlockHeight } = await connection.getLatestBlockhash("finalized");
    transaction.recentBlockhash = blockhash;
    transaction.sign(platform, mintKeypair);

    signature = await connection.sendRawTransaction(transaction.serialize(), {
      skipPreflight: false,
      maxRetries: 3,
      preflightCommitment: "confirmed",
    });

    await recordNftBroadcast(launchedNftId, signature, mintKeypair.publicKey.toBase58());

    const confirmation = await connection.confirmTransaction(
      { signature, blockhash, lastValidBlockHeight },
      "confirmed"
    );

    if (confirmation.value.err) {
      await markNftStatus(launchedNftId, "FAILED", `Transaction failed on-chain: ${JSON.stringify(confirmation.value.err)}`);
      return;
    }
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error while minting.";
    console.error(`Launchpad NFT mint ${launchedNftId}: mint transaction error:`, error);
    await markNftStatus(launchedNftId, "FAILED", message);
    return;
  }

  await markNftStatus(launchedNftId, "COMPLETED");
}
